# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
### Dockerfile for SuzieQ MCP Server
FROM python:3.12-alpine

# Set working directory
WORKDIR /app

# Copy all contents into the image
COPY . .

# Upgrade pip and install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir \
         httpx>=0.28.1 \
         python-dotenv>=1.0.0 \
         "mcp[cli]>=1.6.0"

# Expose any relevant ports if needed (MCP uses stdio, so not typically required)

# Command to run the MCP server
CMD ["python", "main.py"]
